EndScene取り敢えず手直ししたYO(2016.11,22.17:21)
Crocus7724/SengokuConquest pull request #26
Opened 2016-11-22 08:22 UTC by C0114544

試しに、作ってみたやつ。

2016-11-24 03:43 UTC, Crocus7724 commented
ThanksだYO!
でもこのままだとコンパイルが通らなくて哀しみに包まれるから実験のときに相談させてくれYO!

2016-11-24 04:14 UTC, Crocus7724 commented
ref #14

2016-11-25 02:42 UTC, C0114544 commented
取り敢えずGameApplication.current.つけた

2016-11-25 02:58 UTC, Crocus7724 commented on src/sengoku_conquest/scene/EndScene.java
> +        if(GameApplication.current.getTurn() >= 0){
ターンが0以上のときに処理に入ってしまうのでこれは恐らく逆(<=)かな?

2016-11-25 02:58 UTC, Crocus7724 commented on src/sengoku_conquest/scene/EndScene.java
> +        if(GameApplication.current.getMainCharacter().getStatus().getCurrentHp >= 0){
これも上記と一緒で、あとgetCurrentHpに()がないですね(基本的に途中まで入力してctrl+Spaceで出てくるのをエンターする)

2016-11-25 03:00 UTC, Crocus7724 requested changes
コメントで指摘した点+いくつかの修正をよろしくお願いいたします。

2016-11-25 03:03 UTC, Crocus7724 commented
それとimportに`sengoku_conquest.GameApplication`(たぶん)がありません。
Javaのコーディングするときの注意として、基本的にIDE(Android Studio)主導で書いて下さい。私もIDE任せで文法覚えてないのいくつかあります。

2016-11-25 03:06 UTC, Crocus7724 commented
おしい!ほぼほぼ完成してきたけどこのままマージすると他の人もプログラムを実行できなくなってしまうので基本的にビルドできないものはマージできないのです・・・

ここいらへんのことに関しては実験中に相談させて下さい。
ここまでの対応ありがとうございました!!

2016-11-25 05:02 UTC, Crocus7724 commented
OKです!!ありがとうございます!!

2016-11-25 05:02 UTC, merged